#!/usr/bin/env python3
"""Собрать installable-плагин из домена Agent KB.

Домен в `sysadmin-analytics-agent-kb/<domain>/` — источник истины. Плагин в
`plugins/<plugin>/` — производный артефакт: его `references/` генерируются этим скриптом и
править их руками нельзя (следующий прогон перезапишет). Авторскими остаются `SKILL.md`,
`plugin.json` и `agents/`.

Что делает трансформация:

- снимает YAML-frontmatter (в плагине он нужен только в `SKILL.md`);
- перекладывает authority-карточки, на которые ссылается домен, в `references/cards/`;
- переписывает ссылки `../references/<card>.md` -> `cards/<card>.md`, чтобы плагин работал
  без доступа к репозиторию;
- вырезает из карточек секции про артефакты KB (`Skills that may consume this reference`
  и родственные) — в плагине их пути не резолвятся;
- ставит в начало каждого файла маркер происхождения.

Использование:

    python sysadmin-analytics-agent-kb/tools/build_plugin_from_domain.py            # собрать
    python sysadmin-analytics-agent-kb/tools/build_plugin_from_domain.py --check    # для CI
    python .../build_plugin_from_domain.py --plugin video-color                     # один

`--check` ничего не пишет: пересобирает в памяти и сравнивает с тем, что лежит в репо.
Расхождение -> exit 1 со списком файлов. Так домен и плагин не разъезжаются молча.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
KB = ROOT / "sysadmin-analytics-agent-kb"
PLUGINS = ROOT / "plugins"
PACKAGES = KB / "tools" / "plugin_packages.json"

MARKER = (
    "<!-- generated by sysadmin-analytics-agent-kb/tools/build_plugin_from_domain.py "
    "from {src} — edit the source, not this copy -->"
)

FRONTMATTER_RE = re.compile(r"\A---\n.*?\n---\n+", re.DOTALL)
CARD_LINK_RE = re.compile(r"\[([^\]]+)\]\((?:\.\./)+references/([a-z0-9-]+)\.md\)")
SIBLING_CARD_RE = re.compile(r"\[([^\]]+)\]\(\./([a-z0-9-]+)\.md\)")
TITLE_PREFIX_RE = re.compile(r"^# (?:Skill|Rule|Workflow|Agent|Reference): ", re.MULTILINE)
# Секции карточек, описывающие место в KB: в плагине их ссылки никуда не ведут.
KB_ONLY_SECTIONS = (
    "Skills that may consume this reference",
    "Agents that may consume this reference",
    "Agent-facing artifacts that may consume this reference",
)


class BuildError(RuntimeError):
    pass


def read(path: Path) -> str:
    if not path.exists():
        raise BuildError(f"нет источника: {path.relative_to(ROOT).as_posix()}")
    return path.read_text(encoding="utf-8")


def drop_sections(text: str, titles: tuple[str, ...]) -> str:
    for title in titles:
        pattern = re.compile(
            rf"^## {re.escape(title)}\n.*?(?=^## |\Z)", re.DOTALL | re.MULTILINE
        )
        text = pattern.sub("", text)
    return text


def rewrite_card_links(text: str, cards: set[str], depth: str) -> str:
    """`../references/x.md` -> `<depth>x.md`; на неизвестную карточку ссылку снимаем."""

    def repl(m: re.Match) -> str:
        label, card = m.group(1), m.group(2)
        if card in cards:
            return f"[{label}]({depth}{card}.md)"
        return f"{label} (`{card}`, вне пакета)"

    return CARD_LINK_RE.sub(repl, text)


def rewrite_sibling_links(text: str, cards: set[str]) -> str:
    def repl(m: re.Match) -> str:
        label, card = m.group(1), m.group(2)
        if card in cards:
            return m.group(0)
        return f"{label} (`{card}`, вне пакета)"

    return SIBLING_CARD_RE.sub(repl, text)


def normalize(text: str) -> str:
    text = FRONTMATTER_RE.sub("", text)
    text = TITLE_PREFIX_RE.sub("# ", text)
    return text


def stamp(text: str, src: Path) -> str:
    marker = MARKER.format(src=src.relative_to(ROOT).as_posix())
    body = text.strip("\n")
    return f"{marker}\n\n{body}\n"


def is_generated(path: Path) -> bool:
    return path.exists() and path.read_text(encoding="utf-8").startswith("<!-- generated by")


def is_authored(path: Path) -> bool:
    """Файл написан руками: существует и не помечен маркером генератора.

    Такие файлы — чужая территория: их не перезаписывают, не сверяют в `--check` и не
    удаляют как осиротевшие. Так один пакет может смешивать авторские references с
    догенерированными карточками.
    """
    return path.exists() and not is_generated(path)


PLUGIN_CARD_LINK_RE = re.compile(r"\]\(cards/([a-z0-9-]+)\.md\)")


def collect_cards(domain_dir: Path, docs: dict[str, str], explicit, skill_dir: Path) -> list[str]:
    """Какие authority-карточки положить в пакет.

    `auto`               — по ссылкам из документов домена;
    `from-plugin-links`  — по ссылкам `cards/x.md` в уже написанных файлах плагина
                           (для пакетов, где references авторские, а не генерируемые);
    список               — явный перечень.
    """
    if isinstance(explicit, list):
        return sorted(set(explicit))
    if explicit == "from-plugin-links":
        found: set[str] = set()
        refs = skill_dir / "references"
        if refs.exists():
            for md in sorted(refs.glob("*.md")):
                found.update(PLUGIN_CARD_LINK_RE.findall(md.read_text(encoding="utf-8")))
        return sorted(found)
    found = set()
    for src_rel in docs:
        for _, card in CARD_LINK_RE.findall(read(domain_dir / src_rel)):
            found.add(card)
    return sorted(found)


def build_package(name: str, spec: dict) -> dict[str, str]:
    """Вернуть {относительный путь в репо: содержимое} для одного плагина.

    Возвращаются только файлы, которыми владеет генератор. Авторские (`SKILL.md`, ручные
    references, карточки пакетов с `overwrite_cards: false`) в результат не попадают и
    поэтому не участвуют ни в записи, ни в `--check`.
    """
    domain_dir = KB / spec["domain"]
    skill_dir = PLUGINS / name / "skills" / spec["skill"]
    docs: dict[str, str] = spec.get("docs", {})
    cards = collect_cards(domain_dir, docs, spec.get("cards", "auto"), skill_dir)
    card_set = set(cards)
    out: dict[str, str] = {}

    for src_rel, dst_name in docs.items():
        dst = skill_dir / "references" / dst_name
        if is_authored(dst):
            continue
        src = domain_dir / src_rel
        text = normalize(read(src))
        text = rewrite_card_links(text, card_set, depth="cards/")
        out[dst.relative_to(ROOT).as_posix()] = stamp(text, src)

    for card in cards:
        dst = skill_dir / "references" / "cards" / f"{card}.md"
        if is_authored(dst):
            continue
        src = KB / "references" / f"{card}.md"
        text = normalize(read(src))
        text = drop_sections(text, KB_ONLY_SECTIONS)
        text = rewrite_card_links(text, card_set, depth="")
        text = rewrite_sibling_links(text, card_set)
        out[dst.relative_to(ROOT).as_posix()] = stamp(text, src)

    return out


def check_authored_files(name: str, spec: dict) -> list[str]:
    """Файлы, которые генератор не пишет, но без которых плагин не поставится."""
    problems = []
    plugin_json = PLUGINS / name / ".claude-plugin" / "plugin.json"
    skill_md = PLUGINS / name / "skills" / spec["skill"] / "SKILL.md"
    if not plugin_json.exists():
        problems.append(f"{name}: нет .claude-plugin/plugin.json")
    if not skill_md.exists():
        problems.append(f"{name}: нет skills/{spec['skill']}/SKILL.md")
        return problems
    head = skill_md.read_text(encoding="utf-8")
    if not head.startswith("---"):
        problems.append(f"{name}: SKILL.md без frontmatter")
        return problems
    fm = head.split("---", 2)[1]
    for key in ("name:", "description:"):
        if key not in fm:
            problems.append(f"{name}: SKILL.md без {key.rstrip(':')} во frontmatter")
    if f"name: {spec['skill']}" not in fm:
        problems.append(f"{name}: имя скилла в SKILL.md не равно {spec['skill']}")
    return problems


def main() -> int:
    ap = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    ap.add_argument("--check", action="store_true", help="только сверить, ничего не писать")
    ap.add_argument("--plugin", help="собрать/сверить только этот плагин")
    args = ap.parse_args()

    packages = json.loads(PACKAGES.read_text(encoding="utf-8"))
    if args.plugin:
        if args.plugin not in packages:
            print(f"неизвестный плагин: {args.plugin}", file=sys.stderr)
            return 2
        packages = {args.plugin: packages[args.plugin]}

    stale: list[str] = []
    problems: list[str] = []
    written = 0
    for name, spec in sorted(packages.items()):
        problems += check_authored_files(name, spec)
        try:
            files = build_package(name, spec)
        except BuildError as exc:
            problems.append(f"{name}: {exc}")
            continue
        for rel, content in files.items():
            path = ROOT / rel
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current == content:
                continue
            if args.check:
                stale.append(f"{rel} — {'отсутствует' if current is None else 'расходится'}")
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            written += 1
        # осиротевшие файлы прошлых сборок: только те, что помечены генератором,
        # авторские файлы рядом не трогаем
        refs = ROOT / PLUGINS.name / name / "skills" / spec["skill"] / "references"
        if refs.exists():
            for path in sorted(refs.rglob("*.md")):
                rel = path.relative_to(ROOT).as_posix()
                if rel in files:
                    continue
                if not path.read_text(encoding="utf-8").startswith("<!-- generated by"):
                    continue
                if args.check:
                    stale.append(f"{rel} — лишний, источника нет")
                else:
                    path.unlink()
                    written += 1

    if problems:
        print("Plugin packaging failed:", file=sys.stderr)
        for p in problems:
            print("- " + p, file=sys.stderr)
        return 1
    if stale:
        print("Plugin sync failed — перегенерируй плагины:", file=sys.stderr)
        for s in stale:
            print("- " + s, file=sys.stderr)
        return 1
    if args.check:
        print(f"Plugin sync passed ({len(packages)} package(s))")
    else:
        print(f"Plugin build passed ({len(packages)} package(s), {written} file(s) written)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
